package data.utilities

import com.fs.starfarer.api.campaign.StarSystemAPI
import com.fs.starfarer.api.impl.campaign.enc.AbyssalRogueStellarObjectEPEC
import com.fs.starfarer.api.impl.campaign.ids.Tags
import com.fs.starfarer.api.impl.campaign.terrain.HyperspaceAbyssPluginImpl

object MPC_abyssUtils {
    fun setupSystemForAbyss(system: StarSystemAPI) {
        for (jumpPoint in system.autogeneratedJumpPointsInHyper) {
            if (jumpPoint.isStarAnchor) {
                jumpPoint.addTag(Tags.STAR_HIDDEN_ON_MAP)
            }
            var range = HyperspaceAbyssPluginImpl.JUMP_POINT_DETECTED_RANGE
            if (jumpPoint.isGasGiantAnchor) {
                range = HyperspaceAbyssPluginImpl.GAS_GIANT_DETECTED_RANGE
            } else if (jumpPoint.isStarAnchor) {
                range = HyperspaceAbyssPluginImpl.STAR_DETECTED_RANGE
            }

            AbyssalRogueStellarObjectEPEC.setAbyssalDetectedRange(jumpPoint, range)
        }
        for (nascentWell in system.autogeneratedNascentWellsInHyper) {
            AbyssalRogueStellarObjectEPEC.setAbyssalDetectedRange(nascentWell,
                HyperspaceAbyssPluginImpl.NASCENT_WELL_DETECTED_RANGE
            )
        }
        system.addTag(Tags.SYSTEM_ABYSSAL)
    }
}